### ISSUE TITLE
Latest everything, Forge, SpongeForge and Latch and I am crashing with the following error in console. 

### ISSUE THREAD

**Issue by ghost** [IchorDev/Latch#2]
`01.08 13:12:59 [Multicraft] Server stopped
01.08 13:12:59 [Multicraft] Server shut down
01.08 13:12:59 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72]
01.08 13:12:59 [Server] INFO at org.spongepowered.mod.plugin.SpongeModPluginContainer.constructMod(SpongeModPluginContainer.java:296) ~[spongeforge-1.8.9-1890-4.2.0-BETA-1625.jar:1.8.9-1890-4.2.0-BETA-1625]
01.08 13:12:59 [Server] INFO at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051) ~[spongeforge-1.8.9-1890-4.2.0-BETA-1625.jar:1.8.9-1890-4.2.0-BETA-1625]
01.08 13:12:59 [Server] INFO at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025) ~[spongeforge-1.8.9-1890-4.2.0-BETA-1625.jar:1.8.9-1890-4.2.0-BETA-1625]
01.08 13:12:59 [Server] INFO 1 error
01.08 13:12:59 [Server] INFO while locating com.ichorcommunity.latch.Latch
01.08 13:12:59 [Server] INFO at org.spongepowered.common.guice.SpongePluginGuiceModule.configure(SpongePluginGuiceModule.java:68)
01.08 13:12:59 [Server] INFO at com.ichorcommunity.latch.Latch.<init>(Latch.java:81)
01.08 13:12:59 [Server] INFO 1) Error injecting constructor, java.util.NoSuchElementException: No value present
01.08 13:12:59 [Server] INFO com.google.inject.ProvisionException: Unable to provision, see the following errors:
01.08 13:12:59 [Server] Server thread/ERROR [FML]: Caught exception from latch
01.08 13:12:59 [Server] Server thread/ERROR [FML]: The following problems were captured during this phase
`

**Comment by parlough** [comment]
This is because you are running 1.8.9, this plugin only supports Sponge API 5.0.0 which is for Minecraft 1.10.2. For now you would need to switch to 1.10.2, I'll look into creating a downgraded version, but no guarantees.

**Comment by ghost** [comment]
Ok, I guess until then we will just stick with Keys. I hate that as I liked
the look of your plugin.

Jason Brown
_phone:_ 706.266.4346
_address:_ 42 North Ridge Dr Adairsville, GA 30103
_site:_ jsnbrown.com
_email:_ jsnbrown1989@gmail.com
https://www.facebook.com/jsnbrown
https://twitter.com/jsnbrown1989
https://www.instagram.com/jsnbrown1989/

**Comment by parlough** [comment]
We're going to release a backwards compatible version, but have some issues to fix in the main branch first. Watch this issue for updates.

**Comment by parlough** [comment]
Sorry that we never got to this, have been busy. I hope to update Latch soon though, but for now we only plan to support the latest API released by Sponge.
