### ISSUE TITLE
Only one of the chest's in a double chest is protected. 

### ISSUE THREAD

**Issue by Blargmode** [IchorDev/Latch#27]
I'm running latch-0.4.2-S6.0.0 on spongevanilla-1.11.2-7.0.0-BETA-269

If I lock a double chest only the section I clicked on will be protected. Anyone could still click on the other half and take the items. If I try to lock the second half it says "There is already a lock here".

The other plugins I have is:
LuckPerms
Prism
Nucleous
SleepVote
FastAsyncWorldEdit

**Comment by parlough** [comment]
Sorry to hear that this is occurring. This has not been an issue before so I'll definitely look into this as soon as possible (probably later tomorrow). 

Thanks for report!

**Comment by varinyc** [comment]
Can confirm that this still happens on Block19, even as of 1.12

**Comment by parlough** [comment]
I don't have much time this week, but I'll try to fix this tomorrow. If not it'll be this weekend.

**Comment by parlough** [comment]
This was actually a Sponge issue and is fixed in the latest 7.0.0 SpongeForge and the next 7.0.0 build of SpongeVanilla.

**Comment by parlough** [comment]
So it seems it was not completely fixed for block snapshots but the next build of Latch will have it functional. Cheers.
