### ISSUE TITLE
Not able to lock anything (1.12.2)

### ISSUE THREAD

**Issue by L31H4** [IchorDev/Latch#29]
Hello, I have an issue when trying to place locks: https://pastebin.com/GHBD1d1m
it causes no crash, just the lock isn´t placed
I´m on Version 1.12.2 with spongeforge (build 2705) and forge build 2509

**Comment by parlough** [comment]
Yeah I haven't released the fix for this yet. I'll make a release on GitHub tonight that fixes this. 

Sorry!

**Comment by L31H4** [comment]
cool, thx very much for the fast reponse and your effort

**Comment by parlough** [comment]
This should be fixed in the latest Github release you can find here - https://github.com/ichorpowered/latch/releases/tag/v0.4.4

**Comment by L31H4** [comment]
Works fine, top service :)
