### ISSUE TITLE
Donation Chests Don't Function

### ISSUE THREAD

**Issue by ZaneWilkerson** [IchorDev/Latch#31]
Hey _Latch Team_!
I have been experimenting with your plugin, and the **donation** chests do not work. Do you have any reason why this command could be messing up?
**Thanks!**

**Comment by parlough** [comment]
I'll check this out once I get a chance, but do you have any more information? Is the command not working, can you not open the donation chests, can anyone take from the donation chests? Any extra information you could provide would be immensely helpful, thanks!

**Comment by ZaneWilkerson** [comment]
You can open the chests and put stuff in them, it gives you the message in chat that it says it has been created. But the issue is that the players can still interact/take out the items other players got deposited.

**Comment by parlough** [comment]
@Zane-Does-Games Okay thanks for the information, I'll try to find some time to investigate and fix the issue tonight. One last question is what version of Latch and what version of Sponge are you using?

**Comment by aWitch-Doctor** [comment]
The chest is registered as donation. I can click it with /latch info and it shows that everything is good. I put something in the chest, Zane comes by and can open it and take things out. There are no errors in the logs. We are running Sponge Vanilla 7.1.0 Beta 27. Latch version 0.4.7-s7.0.0

also, tab complete doesn't complete the whole word of the command, /latch do(tab) gives /latch donat

**Comment by aWitch-Doctor** [comment]
I tried both with and without grief prevention on the server, issue still happened. Also, LP verbose does not show any perm checks at all for latch. not sure if that matters. I checked verbose for donation chest, private chest and locked door. There wasn't a single entry for latch. 

Only perms players have are "latch.normal" and "latch.normal.create" we are also using the default config. I didn't see anything in there that needed to be changed until it was working.

**Comment by parlough** [comment]
I believe this should be fixed with that commit. I will get a release out as soon as I have a chance, hopefully tonight or tomorrow.

I highly recommend you update your SpongeVanilla build as well, since there are some important fixes that have recently been made.

**Comment by aWitch-Doctor** [comment]
Yep, thank you. just updated to build 33 yesterday.

**Comment by parlough** [comment]
I have just released version 0.4.8 on [Ore](https://ore.spongepowered.org/IchorPowered/Latch/versions/0.4.8). Please test that out and tell me how it goes!
