### ISSUE TITLE
Loading Issue for SpongeForge 7.1.0

### ISSUE THREAD

**Issue by CastorEst** [IchorDev/Latch#35]
Hello Monsieur Meronat!

I have my bug report for you. Latch seems to be providing a couple of error during the server loading process. I don't mean to bother you, I would just be happy if you get to it when you have some spare time. ^^

Full Server Log - https://pastebin.com/BPMCPKTy
Stack Trace - https://pastebin.com/F8YasxZd

Just to note, I run this on custom modpack server with a number of mods, so I'm not sure if the problem is relevant to that or not. Either way, thank you for your time!

**Comment by parlough** [comment]
Thanks for the report. I didn't think this was still an issue, I'll have a fix out by tomorrow.

**Comment by parlough** [comment]
@CastorEst Would you mind trying with this build of Latch? No guarantees on its stability, but would appreciate a test with your modpack!

https://github.com/ichorpowered/latch/releases/tag/v0.5.0-SNAPSHOT

**Comment by parlough** [comment]
Once you confirm this fix I'll make an official release on Ore.

**Comment by CastorEst** [comment]
Ah, forgive me. I hadn't thought you'd reply so soon after I posted the problem.

As for the error, sadly the new release has simply provided me with a different error. ^^"

Server Log - https://pastebin.com/Zusy9E66
Stack Trace - https://pastebin.com/RmhpN002

If you have any questions regarding the server set-up and such, I would be happy to answer them. If the problem is irremediable, then I will also understand. 

Thank you for you for your time no matter the outcome and thanks for going out of your way to help me!

**Comment by vectrixdevelops** [comment]
@parlough It might be a good idea to grab all of the blocks from the registry like you've done for the trap door, since mods may unpredictably remove them from the registry invalidating some of them from the BlockTypes list. Kind of annoying to specify them by string id but, I guess that's that.

**Comment by n0pj** [comment]
I love this plugin.Using even now.
I found a bug. if you are already know this bug, sorry.
This plugin using lock the door, if door is other user locked even can we unlock by any signal.
Example:Pressure plate, Lever, other output signals.

**Comment by parlough** [comment]
@n0pj Unfortunately redstone tracking is a bit tricky especially with mods. Your best bet is to set the `protect_from_redstone` setting in the configuration to true.

I will look into improving redstone protection more soon though as Sponge has improved its tracking a lot since it has been implemented and I now have a better understanding of Sponge's systems.

**Comment by parlough** [comment]
@CastorEst Sorry for the wait, please try this release - https://github.com/ichorpowered/latch/releases/tag/v0.5.0-SNAPSHOT

If it doesn't work, more information about your setup and a clear modlist would be fantastic.

**Comment by CastorEst** [comment]
I'm sorry to say another error and stacktrace are being posted up. ^^"

Server Log - https://pastebin.com/fZ5rbXkY
Stack Trace - https://pastebin.com/vR1iGXCz
Mod List - https://pastebin.com/3mW7WUZN

At this point, I imagine it has started to get frustrating so I would like to point how that I honestly wouldn't blame you if gave up on this bug. If it's too much of hassle, don't put yourself through it.

Thanks for all your help so far, it's great to know that there's such an active developer who cares about solving bugs and other problems with their plugin. I really do appreciate it. ^^

**Comment by parlough** [comment]
@CastorEst Actually this time it was my mistake, I'm sorry. I will handle it the long way and get a new build out soon.

It's a problem with MalisisDoors and/or MalisisCore. I have a messy way to handle it though, and I'll look into MalisisDoors to see if I can fix the root of the problem there.

**Comment by parlough** [comment]
I set up an instance with MalisisCore and MalisisDoors to test before and after the change and we have liftoff. I'll make the 0.5.0 release now. Sorry for the long wait..

**Comment by parlough** [comment]
You can find the 0.5.0 release here - https://github.com/ichorpowered/latch/releases/tag/v0.5.0 which should include the fix for the issue you're having - I will release it on Ore tomorrow if all goes well.

**Comment by CastorEst** [comment]
Hurrah! It works! \o/

It loaded without any errors, and I've managed to lock a door successfully. After all these tries, it finally works. Thank you so much for your help. ^^

It should be ready for release as you mentioned, no further errors have been spotted on my end. 

I would like to make a request in terms of eventually, and when you have spare time, adding support for Conquest doors since they take up a considerable portion of doors on my server and none of them seem to be lockable blocks, but of course, that part's only a personal suggestion, I'm still overjoyed to finally be able to use the plugin!

Anyway, thanks again! ~~I can finally be an evil landlord that locks people in their rooms.~~

**Comment by parlough** [comment]
@CastorEst I'm happy that it's finally working. I'm not 100% sure how Conquest doors work and I'm assuming there's a lot of them, but for now you should be able to do `/latch lockable add` with each door type in your hand to add it to the lockable blocks list.

Next release or soon after I _hope_ to add a mode(which you can enable in config) where all blocks are lockable by default and instead you choose blocks to not make lockable.

**Comment by CastorEst** [comment]
Ah, right. That works as well. I hadn't realized you could make the Conquest doors lockable or any other blocks for that matter. Thank you ever so much! If you need me for anything, feel free to ask. I'd be happy to help!

**Comment by n0pj** [comment]
@parlough aaahhh!!!Sorry,I had not to seen the setting.......Thank you reply.

**Comment by Netholinus** [comment]
Hello, I'm having a similar error as @CastorEst.

Here's the server log: https://pastebin.com/GbWx5RHM
List of mods: https://i.imgur.com/T9avQlF.png

Thank you for your assistance :)
