### ISSUE TITLE
Auto Lock Suggestion

### ISSUE THREAD

**Issue by AdnanMia** [IchorDev/Latch#4]
Hey! It would be great if you would be able to add an auto-locking feature when the users place the items such as chests,furnaces etc.

**Comment by parlough** [comment]
I think this may be a good configuration option, thanks for the suggestion.

For now, if you persist a Latch command by including "-p" in the command or using the command "/lock persist" after you type in a command, every interaction(placing a lockable block or clicking a block) will lock that chest until you type "/lock persist" again. This does not work as a permanent toggle though as it allows you to do nothing else but lock blocks.

**Edit: Oops, didn't mean to close the issue.**

**Comment by parlough** [comment]
This was added as a config option called "auto_lock_on_placement" with 0cc4285faf40c447fa30e2063d03566ea01ca798 and will be part of the next releasing coming soon. Someone with access to server(owner) will need to change this option to true for it to work. 

Thanks for the suggestion. Watch for version 0.2.0 on here or on Ore.
