### ISSUE TITLE
Password Always latches do not unlock

### ISSUE THREAD

**Issue by Barchtic** [IchorDev/Latch#40]
When a latch is set to unlock always, it seems it does not bypass the lock mechanism.
https://i.imgur.com/0olt6yT.png
https://i.imgur.com/MGQt37x.png
https://i.imgur.com/hMe0v5Z.png
Password once seems to work.

Using version 0.50 lock-fix with latest sponge-forge build.

**Comment by vectrixdevelops** [comment]
Fixed in next release.
