### ISSUE TITLE
Bug - 0.3.1 still destroys inventory of chests

### ISSUE THREAD

**Issue by crymates** [IchorDev/Latch#8]
Hey there ;]

Newest version did not fixed the problem completly.
Sometimes items get droped from the chest when destroy, but NOT ALL items and sometimes nothing drops.

Using spongeforge-1.11.2-2226-6.0.0-BETA-2110, the newest one.

Greetz,
Hannes from Germany

**Comment by vectrixdevelops** [comment]
https://github.com/SpongePowered/SpongeCommon/issues/1079 has something to do with it I think.

**Comment by parlough** [comment]
Yeah @connorhartley is probably right, but I'll look into it later today. Thanks for the report.

**Comment by parlough** [comment]
Yeah this 100% seems like a Sponge issue as it happens without locked blocks as well. Will try to escalate the issue as it seems to happen almost 100% of the time.

**Comment by parlough** [comment]
As far as I know this should be fixed in the latest SpongeForge build and will be in the next SpongeVanilla build. Will close this issue once that SpongeVanilla build is released and I have tested it some more. Hooray.

**Comment by vectrixdevelops** [comment]
Yay indeed. :D

**Comment by parlough** [comment]
This has been fixed in the latest releases of SpongeForge and SpongeVanilla - yay :D
