### ISSUE TITLE
Placing an auto-locking block when lock limit was reached denies placement

### ISSUE THREAD

**Issue by turtledude01** [IchorDev/Latch#9]
Basically, if there is a limit on how many locks you can have for a certain block, and you have that ammount locked, it does not let you place them.  This was specifically found with chests.

**Comment by parlough** [comment]
Oh man I did not think of this case, sorry. I'll try my best to get this fixed soon. Appreciate the report as always.

**Comment by parlough** [comment]
This has been fixed in the latest release! Hooray.
